.TH FOOBAR 1 2022-11-24 v1.0
.SH NAME
foobar \- foo all your bars
.SH SYNOPSIS
.B foobar
[\fB\-a\fR \fIarg\fP]
.RB [ \-f | \-\-fu ]
.RB [ \-xyz ]
.IR "bar " ...
.SH DESCRIPTION
.B foobar
takes a list of one or more
.IR bar s
and foos each of them.
.PP
In detail, lorem ipsum dolor sit amet, consectetur adipisicing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.
.SH OPTIONS
.TP
.BI "\-a " arg
Put the apple at
.IR arg .
.TP
.BR \-f ", " \-\-fu
Do a FUBAR instead.
.IP
Note that this can permanently destroy your computer.
.IP \fB\-x\fR
Be exact about it.
.TP
.B -y
Be yucky about it.
.IP \fB-z\fR
Be zucchini about it.
.SH FILES
.TP
.I ~/.cache/foo
This is where the bars are stored.
.SH "SEE ALSO"
.BR man (1),
.BR groff (7),
.BR groff_man (7)
.PP
.I A Brief History of Foo
by Fabian Oscar Oh
.PP
.RI < https://www.example.com/foo/bar.html >
